### PR TITLE
>2% browser support

### PR DESCRIPTION
**Pull request by chrisdukakis**
- Configure babel to support `>2%` browsers
- Rebuild `lib/mam.web.js`

### CODE REVIEW

**Review by mtrabelsi — APPROVED** [review]

**Review by mtrabelsi — CHANGES_REQUESTED** [review]
Transpiler works fine now, however I cant reproduce the same build on my side, the result that I had after the build is much bigger than this PR, something we need to check before merging.

**Comment by chrisdukakis** [comment]
@mtrabelsi interesting, building with `yarn web` should produce deterministic result...
Could you upload a diff of your build against my branch (`git diff ./lib/mam.web.js`)?

**Comment by sobolev-alexey** [comment]
I don't see why this change (2% instead of 5%) is needed. 
Simple run of `yarn web` produces exactly same result.

**Comment by sobolev-alexey** [comment]
Please consider https://github.com/iotaledger/mam.client.js/pull/19 instead

**Comment by chrisdukakis** [comment]
haha, @sobolev-alexey good catch! this is true in my setup as well

**Pull request closed without merging**
