### PR TITLE
Added the future to use alternative attachToTangle functions

### PR DESCRIPTION
**Pull request by IoTMOD**
# Description
This enhancement added the future to use alternative attachToTangle functions (e.g. to use another Node to do the PoW or use a PoW service)

## Type of change
* Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?
* mam.client.js/example/publishAndFetchPublic.js (with and without alternative attachToTangle function)

# Checklist:
* [x]   My code follows the style guidelines for this project
* [x]   I have performed a self-review of my own code
* [x]   New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IoTMOD** [comment]
This is an example how to outsource attachToTangle to powsrv.io:
https://gitlab.com/powsrv.io/js/iota.lib.js.powsrvio/tree/develop#my-first-public-mam-stream-with-pow-done-by-powsrvio

**Comment by obany** [comment]
There is a problem with this code in that by passing the externalAttachToTangle as the second param to init you will break the usage for anyone that is already passing a seed or security to init.

**Comment by obany** [comment]
Also could we use `overrideAttachToTangle` instead of `attachToTangle` for the var name as `attachToTangle ` is the name of functions we can import from PoW modules.

**Comment by IoTMOD** [comment]
Thanks for the feedback, I changed it accordingly.

**Comment by sobolev-alexey** [comment]
I added this functionality to the library, `Mam.init()` function was updated to accept JSON config like 
```
Mam.init({ provider, attachToTangle })
```

**Pull request closed without merging**
