### PR TITLE
Added TypeScript definitions

### PR DESCRIPTION
**Pull request by obany**

### CODE REVIEW

**Comment by Core-pl** [comment]
Hi Martyn,
I tried to import MAM to my node.js project (written in typescript), but I received following message:
`"mam.client.d.ts' is not a module.".`
I put both files: "mam.client.js" and "mam.client.d.ts" in folder /src/external and I tried to import it as 
`import * as Mam from "./external/mam.client.js"`

Can you please guide me, what is the best way to import this library to typescript?

Many thanks,
Mateusz

**Comment by obany** [comment]
Just install it as a normal package.

```
npm install iotaledger/mam.client.js
```

and then in your code you should be able to just use it

```typescript
import * as Mam from "mam.client.js";

Mam.init("https.....");
```

The `typings` entry in `package.json` tells typescript where the definitions are located.

**Comment by Core-pl** [comment]
Thank you for a quick response. I lost whole night on trying to import and fix:
`npm install @iota/mam`
which is an outdated version. Do you know if this is managed by IOTA foundation as well? It would be great to find a way to get rid of this ambiguity.

Today I tried the one you mentioned ( iotaledger/mam.client.js ) and received following error:
```
ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/iotaledger/mam.client.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

I'm on windows, so most likely I don't have git executable to run. Any idea how to fix this?

**Comment by obany** [comment]
@iota/mam is our repo, I will endeavor to get it updated, we just wanted to make sure the master branch was stable first.

I am afraid you will need to install git to get it to install directly from the repo.

**Comment by Core-pl** [comment]
I installed GitHub Desktop  and added path to git.exe and it seems to download correctly now. I keep fingers crossed :)

**Comment by Core-pl** [comment]
I installed GitHub Desktop  and added path to git.exe and it seems to download correctly now. I keep fingers crossed :)

**Comment by Core-pl** [comment]
I confirm it works correctly. Thank you for help.

**Pull request merged**
